# -*- coding: utf-8 -*-
"""preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PPRvFxgFvJqX66UE49PDlNOouG4T402
"""

code = '''
import pandas as pd

# Load datasets
exchange_rate = pd.read_csv("Exchange_Rate.csv", sep=";")
exports = pd.read_csv("Exports.csv", sep=";")
fdi = pd.read_csv("FDI.csv", sep=";")
gdp_growth = pd.read_csv("GDP_Growth.csv", sep=";")
imports = pd.read_csv("Imports.csv", sep=";")
inflation = pd.read_csv("Inflation.csv", sep=";")
population_growth = pd.read_csv("Population_Growth.csv", sep=";")
unemployment = pd.read_csv("Unemployment.csv", sep=";")

def transform_data(df, value_name):
    df_long = pd.melt(
        df,
        id_vars=[
            "Country Name",
            "Country Code",
            "Indicator Name",
            "Indicator Code"
        ],
        var_name="Year",
        value_name=value_name
    )
    return df_long.dropna()

exchange_long = transform_data(exchange_rate, "Exchange_Rate")
exports_long = transform_data(exports, "Exports")
fdi_long = transform_data(fdi, "FDI")
gdp_long = transform_data(gdp_growth, "GDP_Growth")
imports_long = transform_data(imports, "Imports")
inflation_long = transform_data(inflation, "Inflation")
population_long = transform_data(population_growth, "Population_Growth")
unemployment_long = transform_data(unemployment, "Unemployment")

print("Preprocessing selesai")
'''

with open("preprocessing.py", "w") as f:
    f.write(code)

print("preprocessing.py berhasil dibuat")